### ISSUE TITLE
Real World Example

### ISSUE THREAD

**Issue by lukaswelte** [signalfx/swagger-angular-client#2]
It would be great to see the flow and become the complete idea of how angular can work with swagger in a complete example. 

This should be including login and logout handling (redirect the user to login if not authenticated) and using swagger where it is meant to be as a service for the model.
We could use http://petstore.swagger.wordnik.com/api/api-docs also for the extended Example as it provides a OAuth access flow. 

This would really benefit how easy one could adopt using swagger in angular.

**Comment by rszczypka** [comment]
I am soon to start using swagger in a new project in angularjs. It would be great to see a real world example if you managed to build one in the recent months?

**Comment by unsetbit** [comment]
I've added a slightly modified version of how we use this library to the README.md, please let me know if you have any questions or need any clarifications.
